-- Database Name
CREATE DATABASE chartup;

-- Use the Database
USE chartup;

-- Create Tables
CREATE TABLE users (
  id INT(20) PRIMARY KEY AUTO_INCREMENT,
  userid VARCHAR(20) NOT NULL,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  gender VARCHAR(7) NOT NULL,
  password VARCHAR(100) NOT NULL,
  image VARCHAR(500) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  online INT(11)
);

CREATE TABLE messages (
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  msgid VARCHAR(60) NOT NULL,
  sender BIGINT(20) NOT NULL,
  receiver BIGINT(20),
  message TEXT NOT NULL,
  files TEXT,
  date DATETIME NOT NULL,
  seen INT(11) DEFAULT 0,
  received INT(11) DEFAULT 0,
  deleted_sender TINYINT(1) DEFAULT 0,
  deleted_receiver TINYINT(1) DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);